#Config file for all commands and possibilities
#If you have some issues look at the source code https://github.com/PepegaBruh/EasyWarpPlugin
configVersion: 1.0

#By default is set to true
#if is set to true only the owner of the warp can delete itself.
#if is set to false everyone can delete a warp.
deletewarp:
  onlyOwner: false

#By default is true
#If you turn off this you can use this plugin without the permissions
usePermission: false

#By default is set to true
warpRequest:
  #If you set this to false you disable the request to warp to a player
  sendRequest: true
  requestLifetime: "60"



#By default you can't disable the request from a player to him

#Modify this to change the prefix of the messages in the chat
#Dont remove the space at the end of the line, or everything will be written attached
messagiesPrefix: "&5[EasyWarp] "

messagies:
  #In this section you can change the messages for the warp
  #Chenge the number after the "&"  to change the color 
  warp:
    warped: "&6You warped yourself"
    notExist: "&6There is no warp with this name"
    arg: "%cInsert a warp name"
    permission: "&cYou not have this permission"

  #Change this string tho change the messages when a player set a warp
  setwarp:
    succesfullySet: "&6Warp successfully set"
    alredyExist: "&6This warp already exist"
    arg: "&cInsert a valid warp name"
    permission: "&cYou not have this permission"

  delwarp:
    succesfullyDeleted: "&6Successfully deleted the warp"
    permission: "&cYou not have this permission"
    onlyOwner: "&cOnly the owner of this warp can delete it"
    notExixst: "&6There is no warp with this name"
    arg: "&cInsert a valid warp name"

  warps:
    permission: "&cYou not have this permission"
    #Dont modify {warps} and {OwnerName} or will not work
    warpList: "&6Name: &b{warps} &6Owner: &b{OwnerName}"
    noWaroInList: "&cThere is no warp in the list"

  warpreq:
    permission: "&cYou not have this permission"
    warpToYou: "&6WTF ARE YOU DOING"
    succesfullyWarpedsender: "&6You have successfully sent a request to {player}"
    succesfullyWarpedrecivier: "&6You have received a request from {player}"
    offline: "&6This player is offline"
    aredySent: "&6You have already sent a request to {player}"
    arg: "&cInsert a player name"
    expired: "&6The request to {player} expired"
    expiredRecivier: "&6The request from {player} expired"

  warphere:
    permission: "&cYou not have this permission"
    warpToYou: "&6WTF ARE YOU DOING"
    succesfullyWarpedsender: "&6You have successfully sent a request to {player}"
    succesfullyWarpedrecivier: "&6You have received a request from {player}"
    offline: "&6This player is offline"
    alredySent: "&6You have already sent a request to {player}"
    expired: "&6The request to {player} expired"
    expiredRecivier: "&6The request from {player} expired"
    arg: "&cInsert a player name"

  acceptWarp:
    #for the warphere these 2 work in reverse
    acceptedSender: "&6You will bw warped to {player}"
    acceptedRecivier: "&b{player} &6is warping to you"
    ###############################################à
    noRequest: "There is no request"
    toYou: "WHY ARE YOU DOING THIS"
    offline: "&6This player is offline"
    arg: "&cInsert a player name"

  warpno:
    reject: "You removed the request to {player}"
    rejectRecivier : "&6{player} declined your request"
    notResponder: "You cannot decline your request \nType /warpremove {player} to remove the request"
    noRequest: "There is no request from this player"
    toYou: "WHY ARE YOU DOING THIS"
    offline: "&6This player is offline"
    arg: "&cInsert a player name"

  warpRemove:
    removed: "Request destroyed"
    removedRecivier: "The request from {player} was destroyed"
    noRequest: "There is no request to this player"
    noRecivier: "You cannot remove your reuest \nType /warpremove {player} to remove the request"
    toYou: "WHY ARE YOU DOING THIS"
    offline: "This player is offline"
    arg: "Insert a player name"

  warpList:
    noPending: "&6You have no pending requests"
    pending: "&bYou have pending requests from {player}"





    
