#Config file for all commands and possibilities
#If you have some issues look at the source code https://github.com/PepegaBruh/EasyWarpPlugin

#By default is set to true
#if is set to true only the owner of the warp can delete itself.
#if is set to false everyone can delete a warp.
deletewarp:
  onlyOwner: false

#By default is true
#If you turn off this you can use this plugin without the permissions
usePermission: false

#By default is set to true
warpRequest:
  #If you set this to false you disable the request to warp to a player
  sendRequest: true
  requestLifetime: "60"



#By default you can't disable the request from a player to him

#Modify this to change the prefix of the messages in the chat
#Dont remove the space at the end of the line, or everything will be written attached
messagiesPrefix: "&5[EasyWarp] "

messagies:
  #In this section you can change the messages for the warp
  #Chenge the number after the "&"  to change the color 
  warp:
    warped: "&b↑ &8» &7You warped yourself to {warp}"
    notExist: "&b↑ &8» &7There is no warp with this name"
    arg: "&b↑ &8» &cInsert a warp name"
    permission: "&b↑ &8» &cYou not have this permission"

  #Change this string tho change the messages when a player set a warp
  setwarp:
    succesfullySet: "&b↑ &8» &7Warp successfully set"
    alredyExist: "&b↑ &8» &7This warp already exist"
    arg: "&b↑ &8» &cInsert a valid warp name"
    permission: "&b↑ &8» &cYou not have this permission"

  delwarp:
    succesfullyDeleted: "&b↑ &8» &7Successfully deleted the warp"
    permission: "&b↑ &8» &cYou not have this permission"
    onlyOwner: "&b↑ &8» &cOnly the owner of this warp can delete it"
    notExixst: "&b↑ &8» &7There is no warp with this name"
    arg: "&b↑ &8» &cInsert a valid warp name"

  warps:
    permission: "&b↑ &8» &cYou not have this permission"
    #Dont modify {warps} and {OwnerName} or will not work
    warpList: "&b↑ &8» &7Name: &b{warp} &6Owner: &b{OwnerName}"
    noWarpIist: "&b↑ &8» &cThere is no warp in the list"

  warpreq:
    permission: "&b↑ &8» &cYou not have this permission"
    warpToYou: "&b↑ &8» &7WTF ARE YOU DOING"
    succesfullyWarpedsender: "&b↑ &8» &7You have successfully sent a request to {player}"
    succesfullyWarpedrecivier: "&b↑ &8» &7You have received a request from {player}"
    offline: "&b↑ &8» &7This player is offline"
    aredySent: "&b↑ &8» &cYou have already sent a request to {player}"
    arg: "&b↑ &8» &cInsert a player namer"
    expired: "&b↑ &8» &7The request to {player} expired"
    expiredRecivier: "&b↑ &8» &7The request from {player} expired"

  warphere:
    permission: "&b↑ &8» &cYou not have this permission"
    warpToYou: "&b↑ &8» &7WTF ARE YOU DOING"
    succesfullyWarpedsender: "&b↑ &8» &7You have successfully sent a request to {player}"
    succesfullyWarpedrecivier: "&b↑ &8» &7You have received a request from {player}"
    offline: "&b↑ &8» &7This player is offline"
    alredySent: "&b↑ &8» &7You have already sent a request to {player}"
    expired: "&b↑ &8» &7The request to {player} expired"
    expiredRecivier: "&b↑ &8» &7The request from {player} expired"
    arg: "&b↑ &8» &cInsert a player name"

  acceptWarp:
    #for the warphere these 2 work in reverse
    acceptedSender: "&b↑ &8» &7You will bw warped to {player}"
    acceptedRecivier: "&b↑ &8» &7{player} is warping to you"
    ###############################################à
    noRequest: "&b↑ &8» &7There is no request"
    toYou: "&b↑ &8» &7WHY ARE YOU DOING THIS"
    offline: "&b↑ &8» &7This player is offline"
    arg: "&b↑ &8» &cInsert a player name"

  warpno:
    reject: "&b↑ &8» &7You removed the request to {player}"
    rejectRecivier : "&b↑ &8» &7{player} declined your request"
    notResponder: "&b↑ &8» &7You cannot decline your request \nType /warpremove {player} to remove the request"
    noRequest: "&b↑ &8» &7There is no request from this player"
    toYou: "&b↑ &8» &7WHY ARE YOU DOING THIS"
    offline: "&b↑ &8» &7This player is offline"
    arg: "&b↑ &8» &cInsert a player name"

  warpRemove:
    removed: "&b↑ &8» &7Request destroyed"
    removedRecivier: "&b↑ &8» &7The request from {player} was destroyed"
    noRequest: "&b↑ &8» &7There is no request to this player"
    noRecivier: "&b↑ &8» &7You cannot remove your reuest \nType /warpremove {player} to remove the request"
    toYou: "&b↑ &8» &7WHY ARE YOU DOING THIS"
    offline: "&b↑ &8» &7This player is offline"
    arg: "&b↑ &8» &cInsert a player name"

  warpList:
    noPending: "&b↑ &8» &7You have no pending requests"
    pending: "&b↑ &8» &cYou have pending requests from {player}"





    
