#Config file for all commands and possibilities
#If you have some issues look at the source code https://github.com/PepegaBruh/EasyWarpPlugin

#By default is set to true
#if is set to true only the owner of the warp can delete itself.
#if is set to false everyone can delete a warp.
deletewarp:
  onlyOwner: false

#By default is true
#If you turn off this you can use this plugin without the permissions
usePermission: false

#By default is set to true
#If you set this to false you disable the request to warp to a player
sendRequest: true
#  maxRequest: 5

#By default you can't disable the request from a player to him

#Modify this to change the prefix of the messages in the chat
#Dont remove the space at the end of the line, or everything will be written attached
messagiesPrefix: "&5[EasyWarp] "

messagies:
  #In this section you can change the messages for the warp
  #Chenge the number after the "&"  to change the color 
  warp:
    warped: "&6You warped yourself"
    notExist: "&6There is no warp with this name"
    arg: "%cInsert a warp name"
    permission: "&cYou not have this permission"

  #Change this string tho change the messages when a player set a warp
  setwarp:
    succesfullySet: "&6Warp successfully set"
    alredyExist: "&6This warp already exist"
    arg: "&cInsert a valid warp name"
    permission: "&cYou not have this permission"

  delwarp:
    succesfullyDeleted: "&6Successfully deleted the warp"
    permission: "&cYou not have this permission"
    onlyOwner: "&cOnly the owner of this warp can delete it"
    notExixst: "&6There is no warp with this name"
    arg: "&cInsert a valid warp name"

  warps:
    permission: "&cYou not have this permission"
    #Dont modify {warps} and {OwnerName} or will not work
    warpList: "&6Name: &b{warps} &6Owner: &b{OwnerName}"
    noWaroInList: "&cThere is no warp in the list"

  warpreq:
    permission: "&cYou not have this permission"
    warpToYou: "&6WTF ARE YOU DOING"
    succesfullyWarpedsender: "&6You have successfully sent a request to {receiver}"
    succesfullyWarpedrecivier: "&6You have received a request from {sender}"
    offline: "&6This player is offline"
    alredySent: "&6You have alredy sent a request to {recivier}"
    arg: "&cInsert a player name"

  warphere:
    permission: "&cYou not have this permission"
    warpToYou: "&6WTF ARE YOU DOING"
    succesfullyWarpedsender: "&6You have successfully sent a request to {receiver}"
    succesfullyWarpedrecivier: "&6You have received a request from {sender}"
    offline: "&6This player is offline"
    alredySent: "&6You have already sent a request to {recivier}"
    arg: "&cInsert a player name"

  acceptWarp:
    acceptedSender: "&6You will bw warped to {sender}"
    acceptedRecivier: "&b{receiver} &6is warping to you"
    noRequest: "There is no request"
    toYou: "WHY ARE YOU DOING THIS"
    playerOffline:  "&bThis player is offline"

  warpno:
    reject: "&6{receiver} refused your request"

  warpList:
    noPending: "&6You have no pending requests"
    pending: "&bYou have pending requests from {sender}"





    
